### ISSUE TITLE
[BUG] キャッシュを使わずHASCローダでロードを行うとValueErrorが出ることがある

### ISSUE THREAD

**Issue by foo2810** [haselab-dev/sensorutils#19]
**バグの内容**

HASCローダクラスに関するバグ

```python
# キャッシュは作成されていない！
hasc = HASC(dataset_path, cache_path)
queries = {...}
x, y, m = hasc.load(window_size=256, stride=256, queries=queries)
```

**キャッシュが作成されていない状態で**HASCローダでデータをロードする際，何らかの`queries`を指定すると，下記のようなTracebackとともにエラーが出る．

```
Traceback (most recent call last):
  File "E:\project\sensorutils\test.py", line 209, in <module>
    test_hasc()
  File "E:\project\sensorutils\test.py", line 116, in test_hasc
    x, y, label_map = hasc.load(window_size, stride, queries=queries, ftrim=2*100, btrim=2*100, y_labels=['activity', 'gender', 'person'])
  File "E:\project\sensorutils\./src\sensorutils\datasets\hasc.py", line 268, in load
    x_frames = np.concatenate(x_frames)
ValueError: need at least one array to concatenate
```

エラーの内容からsliding-window処理後のフレームの数が0となり，結果として`np.concatenate`で予期しないエラーが発生してしまっている．

**期待される動作**

想定通りの動作をする場合は'queries'によるフィルタリングによっていくつかのデータが残り，そのデータからsliding-windowで切り出されたデータが返されるはずである．

**原因**

sliding-windowの処理には問題はないため，メタデータによるフィルタリング周りが原因であると目星をつけて調べたところ，生成された直後のメタデータ(DataFrame)はすべて文字列で表現されており，これにより`_filter_with_meta`によるフィルタリング時にすべてのデータがはじかれ，上記のようなエラーにつながっていた．

**対処**

メタデータを用意する際に各カラムのdtypeを明示してやればよい．

```python
class HASC(BaseDataset):
    ...

    def __init__(self, path:Path, meta_cache_path:Optional[Path]=None):
        super().__init__(path)
        self.cache_dir_meta = meta_cache_path

        if meta_cache_path is not None:
            if meta_cache_path.exists():
                self.meta = pd.read_csv(str(meta_cache_path), index_col=0)
            else:
                self.meta = load_meta(path)
                self.meta.to_csv(str(meta_cache_path))
        else:
            self.meta = load_meta(path)
 
        # dtypeを明示
        dtypes = {
            'LogVersion': np.float64,
            'Frequency': np.float64,
            'Height(cm)': np.float64,
            'Weight(kg)': np.float64,
            'Pace(cm)': np.float64,
            'HeightOfOneStairStep(cm)': np.float64,
            'UseHistory': np.float64,
            'Count': np.float64,
        }
        self.meta = self.meta.astype(dtypes)
        
        self.label_map = None

        ...
```

**Comment by foo2810** [comment]
修正が完了したのでこれはfix
